spring.application.name=car-sharing-app

spring.datasource.url=jdbc:postgresql://localhost:5432/car_sharing_app
spring.datasource.username=postgres
spring.datasource.password=postg4use
spring.datasource.driver-class-name=org.postgresql.Driver

server.servlet.context-path=/api

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
